#!/usr/bin/env python3
"""
run_sr_acceptance.py
--------------------
Command-line acceptance test for HLS Surface Reflectance containers.

Reads a per-file comparison CSV (generated by notebooks/HLS_SR_acceptance_test.ipynb)
and runs the two statistical tests (Wilcoxon signed-rank + permutation) to produce
a per-band and overall Pass / Fail verdict.

WORKFLOW
--------
1. Run the notebook once per experiment to generate the comparison CSV:
       notebooks/HLS_SR_acceptance_test.ipynb  →  reports/sr_comparison_<exp>.csv

2. Then call this script for the final auditable verdict (no S3 access needed):
       python scripts/run_sr_acceptance.py \\
           --experiment exp2-recompile \\
           --csv        reports/sr_comparison_exp2-recompile.csv

   Or point it at the config and override only the experiment:
       python scripts/run_sr_acceptance.py \\
           --experiment exp2-recompile \\
           --config     config/sr_regression_config.yaml

EXIT CODES
----------
  0  PASS  — all bands pass both statistical tests
  1  FAIL  — one or more bands fail at least one test
  2  ERROR — missing input, bad config, or runtime failure

REPRODUCIBILITY
---------------
Every run writes a timestamped report to --output-dir (default: reports/).
The report includes all per-band p-values, verdicts, and the CLI call used.
"""

import argparse
import csv
import datetime
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Dependencies (all available in the lpdaac_vitals / standard scipy stack)
# ---------------------------------------------------------------------------
try:
    import numpy as np
    import pandas as pd
    from scipy import stats
    import yaml
except ImportError as exc:
    print(f"[ERROR] Missing dependency: {exc}")
    print("        Run: conda activate lpdaac_vitals  (or pip install numpy pandas scipy pyyaml)")
    sys.exit(2)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
FRAMEWORK_ROOT = Path(__file__).resolve().parent.parent
HLS_SCALE_FACTOR = 0.0001

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="run_sr_acceptance.py",
        description="HLS SR container acceptance test — statistical Pass / Fail.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "--experiment",
        default=None,
        metavar="NAME",
        help=(
            "Experiment label, e.g. 'exp2-recompile'.  "
            "Used as a tag in the report filename.  "
            "Also used to auto-locate a CSV named "
            "'reports/sr_comparison_<NAME>.csv' if --csv is not given."
        ),
    )
    p.add_argument(
        "--csv",
        default=None,
        metavar="PATH",
        help=(
            "Path to the per-file comparison CSV produced by the notebook "
            "(Section 6). Overrides the auto-lookup based on --experiment."
        ),
    )
    p.add_argument(
        "--config",
        default=str(FRAMEWORK_ROOT / "config" / "sr_regression_config.yaml"),
        metavar="PATH",
        help="Path to the YAML config file (default: config/sr_regression_config.yaml).",
    )
    p.add_argument(
        "--alpha",
        type=float,
        default=None,
        metavar="FLOAT",
        help="Significance level (default: read from config, fallback 0.05).",
    )
    p.add_argument(
        "--n-permutations",
        type=int,
        default=None,
        metavar="INT",
        help="Permutation test resamples (default: read from config, fallback 9999).",
    )
    p.add_argument(
        "--output-dir",
        default=None,
        metavar="DIR",
        help=(
            "Directory for the report files "
            "(default: read from config, fallback reports/)."
        ),
    )
    p.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress per-band table; only print the final verdict.",
    )
    return p


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def load_config(config_path: str) -> dict:
    if not os.path.exists(config_path):
        return {}
    with open(config_path) as f:
        return yaml.safe_load(f) or {}


# ---------------------------------------------------------------------------
# CSV loading + column normalisation
# ---------------------------------------------------------------------------

COLUMN_ALIASES = {
    # notebook df_results column names
    "pct_nonzero_diff": "pct_nonzero_diff",
    "mean_diff_refl":   "mean_diff_refl",
    "max_abs_diff_refl":"max_abs_diff_refl",
    "filename_pre":     "filename_pre",
    # external CSV column names (prod_vs_dev export)
    "filename_old_container": "filename_pre",
    "filename_new_container": "filename_post",
    "mean_diff":              "_mean_diff_dn",   # DN, needs scaling
    "max_abs_diff":           "_max_abs_diff_dn",# DN, needs scaling
    "pct_nonzero":            "pct_nonzero_diff",
}


def load_comparison_csv(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    # Normalise column names via alias map
    rename = {k: v for k, v in COLUMN_ALIASES.items() if k in df.columns and k != v}
    df = df.rename(columns=rename)
    # Scale DN columns if raw DN was provided
    if "_mean_diff_dn" in df.columns and "mean_diff_refl" not in df.columns:
        df["mean_diff_refl"] = df["_mean_diff_dn"] * HLS_SCALE_FACTOR
    if "_max_abs_diff_dn" in df.columns and "max_abs_diff_refl" not in df.columns:
        df["max_abs_diff_refl"] = df["_max_abs_diff_dn"] * HLS_SCALE_FACTOR
    return df


def extract_band(filepath: str) -> str:
    """Extract band suffix from HLS filename, e.g. 'B01', 'NDVI'."""
    fname = str(filepath).split("/")[-1]
    parts = fname.split(".")
    return parts[-2] if len(parts) >= 2 else fname


def extract_product_type(filepath: str) -> str:
    return "VI" if "_VI" in str(filepath) else "SR"


# ---------------------------------------------------------------------------
# Statistical tests
# ---------------------------------------------------------------------------

def run_tests(
    mean_diffs: np.ndarray,
    alpha: float,
    n_permutations: int,
) -> dict:
    """Run Wilcoxon + permutation test on a per-band vector of mean differences."""
    n = len(mean_diffs)
    all_zero = np.all(mean_diffs == 0)

    # ── Wilcoxon signed-rank ──────────────────────────────────────────────────
    if n >= 2 and not all_zero:
        _, p_wilcox = stats.wilcoxon(mean_diffs, alternative="two-sided")
    else:
        p_wilcox = 1.0 if all_zero else float("nan")

    # ── Permutation test ──────────────────────────────────────────────────────
    if n >= 2 and not all_zero:
        res = stats.permutation_test(
            (mean_diffs,),
            lambda x: np.mean(x),
            permutation_type="samples",
            n_resamples=n_permutations,
            alternative="two-sided",
            random_state=0,
        )
        p_perm = float(res.pvalue)
    else:
        p_perm = 1.0 if all_zero else float("nan")

    w_pass = (p_wilcox >= alpha) if not np.isnan(p_wilcox) else True
    p_pass = (p_perm   >= alpha) if not np.isnan(p_perm)   else True
    band_pass = w_pass and p_pass

    return {
        "wilcoxon_p":      round(p_wilcox, 4) if not np.isnan(p_wilcox) else None,
        "wilcoxon_pass":   w_pass,
        "perm_p":          round(p_perm,   4) if not np.isnan(p_perm)   else None,
        "perm_pass":       p_pass,
        "band_pass":       band_pass,
    }


# ---------------------------------------------------------------------------
# Report formatting
# ---------------------------------------------------------------------------

WIDTH = 88
SEP   = "=" * WIDTH

def fmt_p(val) -> str:
    if val is None:
        return "  n/a  "
    return f"{val:.4f}"

def fmt_verdict(passed: bool) -> str:
    return "PASS" if passed else "FAIL"


def print_report(
    experiment: str,
    csv_path: str,
    df_band: pd.DataFrame,
    alpha: float,
    n_permutations: int,
    overall_pass: bool,
    quiet: bool,
) -> str:
    ts_label = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = []
    lines += [
        SEP,
        "  HLS SR CONTAINER ACCEPTANCE TEST — STATISTICAL REPORT",
        SEP,
        f"  Experiment : {experiment}",
        f"  Input CSV  : {csv_path}",
        f"  Evaluated  : {ts_label}",
        f"  Alpha      : {alpha}  |  Permutations: {n_permutations}",
        f"  Criteria   : Wilcoxon p >= {alpha}  AND  Permutation p >= {alpha}",
        SEP,
    ]

    if not quiet:
        hdr = (
            f"  {'Band':<10} {'Type':<5} {'N':>4}  "
            f"{'Wilcoxon p':>10} {'Wilcoxon':>8}  "
            f"{'Perm p':>8} {'Perm test':>9}  "
            f"{'Verdict':>7}"
        )
        lines += ["", hdr, "  " + "-" * (WIDTH - 2)]
        for _, r in df_band.iterrows():
            row = (
                f"  {r['band']:<10} {r['product_type']:<5} {int(r['n_files']):>4}  "
                f"{fmt_p(r['wilcoxon_p']):>10} {fmt_verdict(r['wilcoxon_pass']):>8}  "
                f"{fmt_p(r['perm_p']):>8} {fmt_verdict(r['perm_pass']):>9}  "
                f"{fmt_verdict(r['band_pass']):>7}"
            )
            lines.append(row)
        lines.append("")

    # Summary counts
    n_bands    = len(df_band)
    n_fail     = int((~df_band["band_pass"]).sum())
    fail_bands = df_band[~df_band["band_pass"]]["band"].tolist()

    lines += [SEP, "  OVERALL VERDICT", ""]
    box_inner = WIDTH - 2
    verdict_str = "PASS" if overall_pass else "FAIL"
    pad = (box_inner - len(verdict_str)) // 2
    lines += [
        "|" + " " * box_inner + "|",
        "|" + " " * pad + verdict_str + " " * (box_inner - pad - len(verdict_str)) + "|",
        "|" + " " * box_inner + "|",
        SEP,
        "",
    ]
    if overall_pass:
        lines.append(
            f"  All {n_bands} bands pass both statistical criteria. "
            "No significant bias detected."
        )
    else:
        lines.append(
            f"  {n_fail}/{n_bands} band(s) fail at least one criterion: "
            + ", ".join(fail_bands)
        )
        lines.append("  Review the per-band table and the comparison CSV for details.")
    lines += ["", SEP]

    # ── Conclusion block ───────────────────────────────────────────────────
    lines += build_conclusion(df_band, alpha)

    report = "\n".join(lines)
    print(report)
    return report


def build_conclusion(df_band: pd.DataFrame, alpha: float) -> list:
    """Build the narrative conclusion section mirroring the notebook cell."""
    n_bands_total    = len(df_band)
    # Wilcoxon failure = systematic bias detected
    has_wilcoxon     = "wilcoxon_pass" in df_band.columns
    n_sig            = int((~df_band["wilcoxon_pass"]).sum()) if has_wilcoxon else 0
    sig_bands        = (df_band[~df_band["wilcoxon_pass"]]["band"].tolist()
                        if has_wilcoxon else [])

    has_diff_col     = "n_files_with_diff" in df_band.columns
    n_any_diff       = int((df_band["n_files_with_diff"] > 0).sum()) if has_diff_col else None
    n_zero_diff      = int((df_band["n_files_with_diff"] == 0).sum()) if has_diff_col else None

    max_diff_row     = df_band.loc[df_band["max_abs_diff_refl"].idxmax()]
    max_pct_row      = df_band.loc[df_band["pct_pixels_changed"].idxmax()]
    mean_diff_global = float(df_band["mean_diff_refl"].mean())
    all_mean_zero    = (df_band["mean_diff_refl"].abs() < 1e-9).all()
    n_granules       = int(df_band["n_files"].iloc[0])

    pct_sig = n_sig / n_bands_total * 100
    if n_sig == 0:
        sig_label = "NOT statistically significant"
        tier = 0
    elif pct_sig <= 25:
        sig_label = f"MARGINALLY significant ({n_sig}/{n_bands_total} bands, p < {alpha})"
        tier = 2
    else:
        sig_label = f"STATISTICALLY SIGNIFICANT ({n_sig}/{n_bands_total} bands, p < {alpha})"
        tier = 3

    if n_sig == 0:
        bias_line = (
            f"   0/{n_bands_total} bands show a statistically significant Wilcoxon bias (p < {alpha})."
            + ("\n   All per-band mean differences = 0.0 reflectance — no systematic offset."
               if all_mean_zero else
               f"\n   Global mean difference across bands: {mean_diff_global:.6f} reflectance units.")
        )
    else:
        bias_line = (
            f"   {n_sig}/{n_bands_total} bands show a statistically significant Wilcoxon bias (p < {alpha}):\n"
            f"   Affected bands: {', '.join(sig_bands)}\n"
            f"   Global mean diff: {mean_diff_global:.6f} reflectance units."
        )

    if tier == 0:
        interp = (
            "   Differences are isolated to a subset of granules and are consistent\n"
            "   with floating-point arithmetic variation between compiler environments.\n"
            "   They are NOT scientifically meaningful."
        )
    elif tier == 2:
        interp = (
            "   A subset of bands shows statistically significant Wilcoxon bias. Differences\n"
            "   are small in magnitude but consistent enough to be detected. Investigate\n"
            "   whether the affected bands share a common processing step."
        )
    else:
        interp = (
            "   Statistically significant bias was detected in a majority of bands.\n"
            "   The magnitude and consistency of differences suggest a real processing\n"
            "   change. Manual inspection of the affected granules and bands is required."
        )

    max_diff_refl = float(max_diff_row["max_abs_diff_refl"])
    ref_compare = (
        f"   Max deviation ({max_diff_refl:.4f} reflectance) vs reference benchmarks:\n"
        f"     - HLS cross-sensor consistency     : ~0.042 reflectance (4.2 %)\n"
        f"     - Atmospheric correction uncertainty: ~0.02–0.05 reflectance"
    )

    diff_count_line = (
        f"   Bit-for-bit identical : {n_zero_diff}/{n_bands_total} bands across all granules\n"
        f"   Bands with any diff   : {n_any_diff}/{n_bands_total}"
        if has_diff_col else
        f"   (n_files_with_diff not available in this CSV format)"
    )

    lines = [
        SEP,
        "  CONCLUSION — STATISTICAL SIGNIFICANCE SUMMARY",
        SEP,
        "",
        f"  OVERALL VERDICT: Differences are {sig_label} (alpha = {alpha}).",
        "",
        f"  Dataset: {n_bands_total} bands/products, {n_granules} granules per band.",
        "",
        "  1. SYSTEMATIC BIAS (Wilcoxon signed-rank test)",
        bias_line,
        "",
        "  2. PERMUTATION TEST",
        f"   {'0' if not any(~df_band['perm_pass']) else str(int((~df_band['perm_pass']).sum()))}"
        f"/{n_bands_total} bands show a significant result under random sign-flipping (p < {alpha}).",
        "",
        "  3. MAGNITUDE OF DIFFERENCES",
        f"   Largest max |diff|    : {max_diff_row['band']} — "
        f"{max_diff_refl:.4f} reflectance units"
        f" (= {int(max_diff_refl / HLS_SCALE_FACTOR)} DN)",
        f"   Largest % pix changed : {max_pct_row['band']} — {float(max_pct_row['pct_pixels_changed']):.5f}% of pixels",
        diff_count_line,
        "",
        "  4. INTERPRETATION",
        interp,
        ref_compare,
        "",
        SEP,
    ]
    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = build_parser()
    args   = parser.parse_args()

    # ── Load config ────────────────────────────────────────────────────────
    cfg = load_config(args.config)
    stat_cfg = cfg.get("statistical_testing", {})

    alpha         = args.alpha          or stat_cfg.get("alpha",          0.05)
    n_permutations= args.n_permutations or stat_cfg.get("n_permutations", 9999)
    output_dir    = args.output_dir     or cfg.get("output", {}).get("report_dir",
                    str(FRAMEWORK_ROOT / "reports"))
    output_dir    = os.path.abspath(output_dir)
    os.makedirs(output_dir, exist_ok=True)

    experiment = args.experiment or "unknown_experiment"

    # ── Locate input CSV ───────────────────────────────────────────────────
    csv_path = args.csv
    if not csv_path:
        # Auto-discover: reports/sr_comparison_<experiment>.csv
        auto = os.path.join(output_dir, f"sr_comparison_{experiment}.csv")
        if os.path.exists(auto):
            csv_path = auto
        else:
            print(
                f"[ERROR] No --csv given and auto-lookup failed: {auto}\n"
                "        Run the notebook (Section 6) first to generate the comparison CSV,\n"
                "        then re-run this script with --csv <path>."
            )
            sys.exit(2)

    if not os.path.exists(csv_path):
        print(f"[ERROR] CSV not found: {csv_path}")
        sys.exit(2)

    # ── Load + enrich ──────────────────────────────────────────────────────
    try:
        df = load_comparison_csv(csv_path)
    except Exception as exc:
        print(f"[ERROR] Failed to read CSV: {exc}")
        sys.exit(2)

    # ── Detect CSV format ─────────────────────────────────────────────────
    # Format A: aggregated per-band stats (wilcoxon_p + perm_p already present)
    #           → produced by notebook Section 7 / statistical_tests_*.csv
    # Format B: per-file comparison results (filename_pre, mean_diff_refl …)
    #           → produced by notebook Section 6 / df_results CSV
    is_stats_csv = {"wilcoxon_p", "perm_p", "band"}.issubset(df.columns)

    if is_stats_csv:
        print(f"\nDetected aggregated stats CSV — skipping recomputation.")
        # Derive pass/fail from stored p-values
        df["wilcoxon_pass"] = df["wilcoxon_p"].apply(
            lambda p: (p >= alpha) if pd.notna(p) else True)
        df["perm_pass"]     = df["perm_p"].apply(
            lambda p: (p >= alpha) if pd.notna(p) else True)
        df["band_pass"]     = df["wilcoxon_pass"] & df["perm_pass"]
        df_band = df.sort_values(["product_type", "band"])
    else:
        # Format B: raw per-file results — run tests from scratch
        if "filename_pre" not in df.columns:
            print(
                "[ERROR] Cannot find a 'filename_pre' or 'filename_old_container' column.\n"
                "        Provide either:\n"
                "          • A per-file comparison CSV from notebook Section 6, or\n"
                "          • An aggregated stats CSV with 'band', 'wilcoxon_p', 'perm_p'."
            )
            sys.exit(2)

        df["band"]         = df["filename_pre"].apply(extract_band)
        df["product_type"] = df["filename_pre"].apply(extract_product_type)

        required = {"mean_diff_refl", "max_abs_diff_refl", "pct_nonzero_diff"}
        missing  = required - set(df.columns)
        if missing:
            print(f"[ERROR] CSV is missing required columns: {missing}")
            sys.exit(2)

        print(f"\nRunning statistical tests  (alpha={alpha}, permutations={n_permutations})...")
        band_rows = []
        for band, grp in df.groupby("band"):
            mean_diffs = grp["mean_diff_refl"].values
            result = run_tests(mean_diffs, alpha, n_permutations)
            band_rows.append({
                "band":              band,
                "product_type":      grp["product_type"].iloc[0],
                "n_files":           len(grp),
                "n_files_with_diff": int((grp["pct_nonzero_diff"] > 0).sum()),
                "mean_diff_refl":    round(float(np.mean(mean_diffs)), 6),
                "max_abs_diff_refl": round(float(grp["max_abs_diff_refl"].max()), 6),
                "pct_pixels_changed":round(float(grp["pct_nonzero_diff"].max()), 5),
                **result,
            })
        df_band = pd.DataFrame(band_rows).sort_values(["product_type", "band"])
    overall_pass = bool(df_band["band_pass"].all())

    # ── Print report ───────────────────────────────────────────────────────
    report_text = print_report(
        experiment, csv_path, df_band,
        alpha, n_permutations, overall_pass,
        args.quiet,
    )

    # ── Save outputs ───────────────────────────────────────────────────────
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    tag = experiment.replace("/", "_")

    # Per-band results CSV
    results_csv = os.path.join(output_dir, f"sr_acceptance_{tag}_{ts}.csv")
    df_band.to_csv(results_csv, index=False)

    # Text report
    report_txt = os.path.join(output_dir, f"sr_acceptance_{tag}_{ts}.txt")
    with open(report_txt, "w") as f:
        # Record the exact command used for full reproducibility
        f.write(f"# Command: python {' '.join(sys.argv)}\n\n")
        f.write(report_text + "\n")

    print(f"\n  Reports saved to:")
    print(f"    {results_csv}")
    print(f"    {report_txt}\n")

    sys.exit(0 if overall_pass else 1)


if __name__ == "__main__":
    main()
